services:
  cpp:
    build:
      context: ./docker/cpp
      dockerfile: Dockerfile
    container_name: cpp
    command: tail -f /dev/null
    profiles:
      - cpp

  pypy:
    build:
      context: ./docker/pypy
      dockerfile: Dockerfile
    container_name: pypy
    command: tail -f /dev/null
    profiles:
      - pypy

  python:
    build:
      context: ./docker/python
      dockerfile: Dockerfile
    container_name: python
    command: tail -f /dev/null
    profiles:
      - python

  ruby:
    build:
      context: ./docker/ruby
      dockerfile: Dockerfile
    container_name: ruby
    command: tail -f /dev/null
    profiles:
      - ruby

  rust:
    build:
      context: ./docker/rust
      dockerfile: Dockerfile
    container_name: rust
    command: tail -f /dev/null
    profiles:
      - rust
